[target.aarch64-linux-android]
linker = "/home/chateaulav/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
ar = "/home/chateaulav/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi34-clang"
ar = "llvm-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android34-clang"
ar = "llvm-ar"

[target.i686-linux-android]
linker = "i686-linux-android34-clang"
ar = "llvm-ar"
