name: quantumzero_dart_sdk
description: A Dart SDK for the QuantumZero identity platform
version: 1.0.0
environment:
  sdk: ^3.5.4

dependencies:
  cryptography: ^2.9.0
  benchmark_harness: ^2.3.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
